
<recipetype:create:mechanical_crafting>.addMirroredRecipe("mirrorized", 
<item:kubejs:creator_sword>, 
[

[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:mithril_casing>,
<item:create_dd:blaze_gold_casing>,
<item:kubejs:creator_ingot>],

[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:shadow_steel_casing>,
<item:create_dd:stargaze_singularity_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:refined_radiance_casing>,
<item:create_dd:blaze_gold_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>],

[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:shadow_steel_casing>,
<item:create_dd:mithril_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:blaze_gold_casing>,
<item:create_dd:stargaze_singularity_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],

[<item:minecraft:air>, 
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:mithril_casing>,
<item:create_dd:refined_radiance_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:blaze_gold_block>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:stargaze_singularity_casing>,
<item:create_dd:shadow_steel_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:refined_radiance_block>,
<item:kubejs:creator_ingot>,
<item:create_dd:refined_radiance_block>,
<item:create_dd:blaze_gold_casing>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],




[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:mithril_block>,
<item:create_dd:blaze_gold_block>,
<item:create_dd:mithril_block>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:create_dd:stargaze_singularity_block>,
<item:create_dd:shadow_steel_block>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:vintageimprovements:calorite_rod>,
<item:kubejs:creator_ingot>,
<item:create_dd:blaze_gold_block>,
<item:create_dd:shadow_steel_block>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:minecraft:air>, 
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:vintageimprovements:calorite_rod>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:create_dd:refined_radiance_block>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:kubejs:creator_ingot>, 
<item:kubejs:creator_ingot>,
<item:vintageimprovements:calorite_rod>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:kubejs:creator_ingot>, 
<item:minecraft:air>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>],


[<item:kubejs:creator_ingot>, 
<item:kubejs:creator_ingot>,
<item:kubejs:creator_ingot>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>,
<item:minecraft:air>]



]);
